apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jd-activity-server
  namespace: meta
spec:
  serviceName: "jd-activity-server"
  replicas: 1
  selector:
    matchLabels:
      app: jd-activity-server
  template:
    metadata:
      annotations:
        commit_id: "${CI_COMMIT_ID}"
      labels:
        app: jd-activity-server
    spec:
      containers:
        - name: jd-activity-server
          image: registry.cn-shenzhen.aliyuncs.com/yffjglcms/jd-activity-server:uat
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: WECOMCHAN_SEND_KEY   #创建新的环境变量名称
              valueFrom:
                secretKeyRef: # 调用的key是什么
                  name: wecomchan-secret       #变量的值来自于 wecomchan-secret
                  key: send_key       # send_key里面的值
            - name: WECOMCHAN_URL
              valueFrom:
                secretKeyRef:
                  name: wecomchan-secret
                  key: url
            - name: JD_ACTIVITY_GIST_ID
              valueFrom:
                secretKeyRef:
                  name: gist-secret
                  key: gist_id
            - name: JD_ACTIVITY_GIST_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gist-secret
                  key: gist_token
      imagePullSecrets:
        - name: regcred
  podManagementPolicy: "Parallel"

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: jd-activity-server
  name: jd-activity-server
  namespace: meta
spec:
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 32010
  type: NodePort
  selector:
    app: jd-activity-server